version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_NAME=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USERNAME=${DATABASE_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: backend
    build:
      context: .
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

volumes:
  postgres_data: