spring:
  datasource:
    dbname: ${DATABASE_NAME:postgres}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/${DATABASE_NAME:postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
